THEMES = {
    # ============================================================
    #                    ТЁМНЫЕ (dark)
    # ============================================================
    "dark": {
        "name": "🌙 Тёмная",
        "category": "dark",
        "BG": "#1e1e1e",
        "BG_CARD": "#2a2a2a",
        "BG_INPUT": "#333333",
        "FG": "#e0e0e0",
        "FG_DIM": "#888888",
        "ACCENT": "#e62117",
        "ACCENT_HOVER": "#ff3b30",
        "ACCENT_PRESS": "#b71c1c",
        "BORDER": "#3a3a3a",
        "BORDER_HOVER": "#e62117",
        "DISABLED": "#3a3a3a",
        "DISABLED_FG": "#666",
    },
    "red": {
        "name": "🔥 Красная",
        "category": "dark",
        "BG": "#2a0a0a",
        "BG_CARD": "#3a1010",
        "BG_INPUT": "#4a1a1a",
        "FG": "#ffdddd",
        "FG_DIM": "#aa7777",
        "ACCENT": "#ff3b30",
        "ACCENT_HOVER": "#ff6b60",
        "ACCENT_PRESS": "#c02020",
        "BORDER": "#5a2020",
        "BORDER_HOVER": "#ff3b30",
        "DISABLED": "#3a1a1a",
        "DISABLED_FG": "#886666",
    },
    "ocean": {
        "name": "🌊 Ocean",
        "category": "dark",
        "BG": "#0a1929",
        "BG_CARD": "#0f2438",
        "BG_INPUT": "#15304a",
        "FG": "#d4e4f7",
        "FG_DIM": "#6a8fb5",
        "ACCENT": "#4db8ff",
        "ACCENT_HOVER": "#77ccff",
        "ACCENT_PRESS": "#2a8fd4",
        "BORDER": "#1e3a54",
        "BORDER_HOVER": "#4db8ff",
        "DISABLED": "#0f2438",
        "DISABLED_FG": "#3d5870",
    },
    "forest": {
        "name": "🌲 Forest",
        "category": "dark",
        "BG": "#0d1a0d",
        "BG_CARD": "#142614",
        "BG_INPUT": "#1c331c",
        "FG": "#d4ecd4",
        "FG_DIM": "#6a9a6a",
        "ACCENT": "#4ade80",
        "ACCENT_HOVER": "#77eaa0",
        "ACCENT_PRESS": "#2ab85e",
        "BORDER": "#234023",
        "BORDER_HOVER": "#4ade80",
        "DISABLED": "#142614",
        "DISABLED_FG": "#3d5a3d",
    },
    "sunset": {
        "name": "🌅 Sunset",
        "category": "dark",
        "BG": "#1a0f1a",
        "BG_CARD": "#2a1828",
        "BG_INPUT": "#3a2238",
        "FG": "#ffe4d4",
        "FG_DIM": "#b5859a",
        "ACCENT": "#ff6b9d",
        "ACCENT_HOVER": "#ff99bb",
        "ACCENT_PRESS": "#d44a7a",
        "BORDER": "#4a2850",
        "BORDER_HOVER": "#ff6b9d",
        "DISABLED": "#2a1828",
        "DISABLED_FG": "#6a4560",
    },
    "grape": {
        "name": "🍇 Grape",
        "category": "dark",
        "BG": "#140a1a",
        "BG_CARD": "#20102a",
        "BG_INPUT": "#2c1838",
        "FG": "#e8d4f7",
        "FG_DIM": "#9070aa",
        "ACCENT": "#a855f7",
        "ACCENT_HOVER": "#c077ff",
        "ACCENT_PRESS": "#7a3ac4",
        "BORDER": "#3a2050",
        "BORDER_HOVER": "#a855f7",
        "DISABLED": "#20102a",
        "DISABLED_FG": "#5a4070",
    },
    "amber": {
        "name": "🍊 Amber",
        "category": "dark",
        "BG": "#1a1408",
        "BG_CARD": "#2a2010",
        "BG_INPUT": "#3a2c18",
        "FG": "#f7e4c4",
        "FG_DIM": "#aa8a55",
        "ACCENT": "#f59e0b",
        "ACCENT_HOVER": "#fbbf24",
        "ACCENT_PRESS": "#d47708",
        "BORDER": "#4a3818",
        "BORDER_HOVER": "#f59e0b",
        "DISABLED": "#2a2010",
        "DISABLED_FG": "#6a5540",
    },
    "coffee": {
        "name": "☕ Coffee",
        "category": "dark",
        "BG": "#1a120a",
        "BG_CARD": "#261a10",
        "BG_INPUT": "#33241a",
        "FG": "#f0dcc4",
        "FG_DIM": "#a08560",
        "ACCENT": "#c77b3a",
        "ACCENT_HOVER": "#e0965a",
        "ACCENT_PRESS": "#a05e24",
        "BORDER": "#40301e",
        "BORDER_HOVER": "#c77b3a",
        "DISABLED": "#261a10",
        "DISABLED_FG": "#6a5540",
    },
    "sakura": {
        "name": "🌸 Sakura",
        "category": "dark",
        "BG": "#1a1216",
        "BG_CARD": "#2a1e24",
        "BG_INPUT": "#3a2a32",
        "FG": "#f7e0ea",
        "FG_DIM": "#b5859a",
        "ACCENT": "#ff8fb0",
        "ACCENT_HOVER": "#ffb0cc",
        "ACCENT_PRESS": "#d46688",
        "BORDER": "#4a2e3a",
        "BORDER_HOVER": "#ff8fb0",
        "DISABLED": "#2a1e24",
        "DISABLED_FG": "#6a4a5a",
    },
    "vampire": {
        "name": "🧛‍♂️ Bloody",
        "category": "dark",
        "BG": "#0d0208",
        "BG_CARD": "#1a0a0f",
        "BG_INPUT": "#2a1018",
        "FG": "#e0c0c8",
        "FG_DIM": "#804858",
        "ACCENT": "#ff0040",
        "ACCENT_HOVER": "#ff4477",
        "ACCENT_PRESS": "#aa0022",
        "BORDER": "#3a1520",
        "BORDER_HOVER": "#ff0040",
        "DISABLED": "#1a0a0f",
        "DISABLED_FG": "#5a2a35",
    },
    "lavender": {
        "name": "💜 Lavender",
        "category": "dark",
        "BG": "#1a1420",
        "BG_CARD": "#261e30",
        "BG_INPUT": "#342a44",
        "FG": "#e8ddf0",
        "FG_DIM": "#9a8aad",
        "ACCENT": "#b19cd9",
        "ACCENT_HOVER": "#c8b8e8",
        "ACCENT_PRESS": "#8a78b0",
        "BORDER": "#443a55",
        "BORDER_HOVER": "#b19cd9",
        "DISABLED": "#261e30",
        "DISABLED_FG": "#5a4d70",
    },
    "mint": {
        "name": "🌿 Mint",
        "category": "dark",
        "BG": "#0f1a16",
        "BG_CARD": "#162822",
        "BG_INPUT": "#1f3630",
        "FG": "#d4f0e4",
        "FG_DIM": "#6a9a85",
        "ACCENT": "#5eead4",
        "ACCENT_HOVER": "#88f5e3",
        "ACCENT_PRESS": "#3ab89f",
        "BORDER": "#1a4538",
        "BORDER_HOVER": "#5eead4",
        "DISABLED": "#162822",
        "DISABLED_FG": "#3d6a5a",
    },
    "ruby": {
        "name": "💎 Ruby",
        "category": "dark",
        "BG": "#1a0a10",
        "BG_CARD": "#2a1018",
        "BG_INPUT": "#3a1820",
        "FG": "#f0d4dc",
        "FG_DIM": "#a07080",
        "ACCENT": "#e0115f",
        "ACCENT_HOVER": "#ff4488",
        "ACCENT_PRESS": "#a80840",
        "BORDER": "#4a1830",
        "BORDER_HOVER": "#e0115f",
        "DISABLED": "#2a1018",
        "DISABLED_FG": "#6a4050",
    },
    "midnight": {
        "name": "🌌 Midnight",
        "category": "dark",
        "BG": "#0a0a1a",
        "BG_CARD": "#14142a",
        "BG_INPUT": "#1e1e3a",
        "FG": "#d4d4f0",
        "FG_DIM": "#6a6a9a",
        "ACCENT": "#6a5acd",
        "ACCENT_HOVER": "#8878dd",
        "ACCENT_PRESS": "#4a3aad",
        "BORDER": "#2a2a4a",
        "BORDER_HOVER": "#6a5acd",
        "DISABLED": "#14142a",
        "DISABLED_FG": "#3d3d66",
    },

    # ============================================================
    #                    СВЕТЛЫЕ (light)
    # ============================================================
    "light": {
        "name": "🌸 Бежевая",
        "category": "light",
        "BG": "#f0ebe0",
        "BG_CARD": "#faf6ee",
        "BG_INPUT": "#e8e0d0",
        "FG": "#3a3028",
        "FG_DIM": "#8a7a6a",
        "ACCENT": "#c94a3a",
        "ACCENT_HOVER": "#e05a4a",
        "ACCENT_PRESS": "#a83a2a",
        "BORDER": "#d8cdb8",
        "BORDER_HOVER": "#c94a3a",
        "DISABLED": "#e0d8c8",
        "DISABLED_FG": "#a89888",
    },
    "ice": {
        "name": "🧊 Ice",
        "category": "light",
        "BG": "#e8f0f7",
        "BG_CARD": "#f5f9fc",
        "BG_INPUT": "#d4e2ef",
        "FG": "#1a2a3a",
        "FG_DIM": "#6a859a",
        "ACCENT": "#0ea5e9",
        "ACCENT_HOVER": "#38bdf8",
        "ACCENT_PRESS": "#0284c7",
        "BORDER": "#c4d4e4",
        "BORDER_HOVER": "#0ea5e9",
        "DISABLED": "#d4e2ef",
        "DISABLED_FG": "#a0b4c4",
    },

    # ============================================================
    #                    ПРАЗДНИКИ (holiday)
    # ============================================================
    "doomsday": {
        "name": "💀 Doomsday (21.12)",
        "category": "holiday",
        "BG": "#1a0505",
        "BG_CARD": "#2a0808",
        "BG_INPUT": "#3a0c0c",
        "FG": "#ffcccc",
        "FG_DIM": "#aa6666",
        "ACCENT": "#ff0000",
        "ACCENT_HOVER": "#ff4444",
        "ACCENT_PRESS": "#990000",
        "BORDER": "#4a1010",
        "BORDER_HOVER": "#ff0000",
        "DISABLED": "#2a0808",
        "DISABLED_FG": "#664444",
    },
    "halloween": {
        "name": "🎃 Хэллоуин (31.10)",
        "category": "holiday",
        "BG": "#1a0f00",
        "BG_CARD": "#2a1800",
        "BG_INPUT": "#3a2200",
        "FG": "#ffd699",
        "FG_DIM": "#aa8855",
        "ACCENT": "#ff8800",
        "ACCENT_HOVER": "#ffaa33",
        "ACCENT_PRESS": "#cc5500",
        "BORDER": "#4a2800",
        "BORDER_HOVER": "#ff8800",
        "DISABLED": "#2a1800",
        "DISABLED_FG": "#886633",
    },
    "newyear": {
        "name": "🎄 Новый год (31.12)",
        "category": "holiday",
        "BG": "#0a1a0a",
        "BG_CARD": "#0f2a0f",
        "BG_INPUT": "#143a14",
        "FG": "#ccffcc",
        "FG_DIM": "#88aa88",
        "ACCENT": "#e62117",
        "ACCENT_HOVER": "#ff3b30",
        "ACCENT_PRESS": "#b71c1c",
        "BORDER": "#1a4a1a",
        "BORDER_HOVER": "#e62117",
        "DISABLED": "#0f2a0f",
        "DISABLED_FG": "#668866",
    },
    "march8": {
        "name": "🌸 8 марта",
        "category": "holiday",
        "BG": "#2a0a1a",
        "BG_CARD": "#3a0f2a",
        "BG_INPUT": "#4a143a",
        "FG": "#ffd6e8",
        "FG_DIM": "#aa7788",
        "ACCENT": "#ff66b3",
        "ACCENT_HOVER": "#ff99cc",
        "ACCENT_PRESS": "#cc3388",
        "BORDER": "#5a2050",
        "BORDER_HOVER": "#ff66b3",
        "DISABLED": "#3a0f2a",
        "DISABLED_FG": "#886677",
    },
    "september1": {
        "name": "🎒 1 сентября",
        "category": "holiday",
        "BG": "#1a1408",
        "BG_CARD": "#2a2210",
        "BG_INPUT": "#3a3018",
        "FG": "#ffeedd",
        "FG_DIM": "#aa9070",
        "ACCENT": "#ff8c00",
        "ACCENT_HOVER": "#ffaa33",
        "ACCENT_PRESS": "#cc5500",
        "BORDER": "#4a3010",
        "BORDER_HOVER": "#ff8c00",
        "DISABLED": "#2a2210",
        "DISABLED_FG": "#886644",
    },
    "feb14": {
        "name": "❤️ 14 февраля",
        "category": "holiday",
        "BG": "#1a0a10",
        "BG_CARD": "#2a1018",
        "BG_INPUT": "#3a1820",
        "FG": "#ffe0ea",
        "FG_DIM": "#aa7088",
        "ACCENT": "#ff2d6f",
        "ACCENT_HOVER": "#ff6699",
        "ACCENT_PRESS": "#cc1555",
        "BORDER": "#4a1830",
        "BORDER_HOVER": "#ff2d6f",
        "DISABLED": "#2a1018",
        "DISABLED_FG": "#885566",
    },
    "april12": {
        "name": "🚀 12 апреля",
        "category": "holiday",
        "BG": "#05050f",
        "BG_CARD": "#0f0f1f",
        "BG_INPUT": "#1a1a2f",
        "FG": "#dde5ff",
        "FG_DIM": "#7080aa",
        "ACCENT": "#4d8cff",
        "ACCENT_HOVER": "#77aaff",
        "ACCENT_PRESS": "#2a66cc",
        "BORDER": "#1a2a4a",
        "BORDER_HOVER": "#4d8cff",
        "DISABLED": "#0f0f1f",
        "DISABLED_FG": "#556688",
    },
    "may1": {
        "name": "🎉 1 мая",
        "category": "holiday",
        "BG": "#0a1a08",
        "BG_CARD": "#102a10",
        "BG_INPUT": "#1a3a18",
        "FG": "#ddffdd",
        "FG_DIM": "#80aa80",
        "ACCENT": "#4dd94d",
        "ACCENT_HOVER": "#77ff77",
        "ACCENT_PRESS": "#2aaa2a",
        "BORDER": "#1a4a1a",
        "BORDER_HOVER": "#4dd94d",
        "DISABLED": "#102a10",
        "DISABLED_FG": "#668866",
    },

    # ============================================================
    #                    ПРОГРАММИСТСКИЕ (code)
    # ============================================================
    "dracula": {
        "name": "🧛 Dracula",
        "category": "code",
        "BG": "#282a36",
        "BG_CARD": "#313342",
        "BG_INPUT": "#3d4050",
        "FG": "#f8f8f2",
        "FG_DIM": "#6272a4",
        "ACCENT": "#bd93f9",
        "ACCENT_HOVER": "#d0b0ff",
        "ACCENT_PRESS": "#9b6fd4",
        "BORDER": "#44475a",
        "BORDER_HOVER": "#bd93f9",
        "DISABLED": "#313342",
        "DISABLED_FG": "#4d5066",
    },
    "nord": {
        "name": "❄️ Nord",
        "category": "code",
        "BG": "#2e3440",
        "BG_CARD": "#3b4252",
        "BG_INPUT": "#434c5e",
        "FG": "#eceff4",
        "FG_DIM": "#7b88a1",
        "ACCENT": "#88c0d0",
        "ACCENT_HOVER": "#8fbcbb",
        "ACCENT_PRESS": "#5e81ac",
        "BORDER": "#4c566a",
        "BORDER_HOVER": "#88c0d0",
        "DISABLED": "#3b4252",
        "DISABLED_FG": "#616e88",
    },
    "gruvbox": {
        "name": "🟠 Gruvbox",
        "category": "code",
        "BG": "#282828",
        "BG_CARD": "#3c3836",
        "BG_INPUT": "#504945",
        "FG": "#ebdbb2",
        "FG_DIM": "#a89984",
        "ACCENT": "#d79921",
        "ACCENT_HOVER": "#fabd2f",
        "ACCENT_PRESS": "#b57614",
        "BORDER": "#665c54",
        "BORDER_HOVER": "#d79921",
        "DISABLED": "#3c3836",
        "DISABLED_FG": "#7c6f64",
    },
    "tokyo": {
        "name": "🌃 Tokyo Night",
        "category": "code",
        "BG": "#1a1b26",
        "BG_CARD": "#24283b",
        "BG_INPUT": "#2f3549",
        "FG": "#c0caf5",
        "FG_DIM": "#565f89",
        "ACCENT": "#7aa2f7",
        "ACCENT_HOVER": "#89ddff",
        "ACCENT_PRESS": "#5a78b8",
        "BORDER": "#3b4261",
        "BORDER_HOVER": "#7aa2f7",
        "DISABLED": "#24283b",
        "DISABLED_FG": "#414868",
    },
    "catppuccin": {
        "name": "🐱 Catppuccin",
        "category": "code",
        "BG": "#1e1e2e",
        "BG_CARD": "#313244",
        "BG_INPUT": "#45475a",
        "FG": "#cdd6f4",
        "FG_DIM": "#7f849c",
        "ACCENT": "#cba6f7",
        "ACCENT_HOVER": "#f5c2e7",
        "ACCENT_PRESS": "#9d7cd8",
        "BORDER": "#585b70",
        "BORDER_HOVER": "#cba6f7",
        "DISABLED": "#313244",
        "DISABLED_FG": "#6c7086",
    },

    # ============================================================
    #                    НЕОН (neon)
    # ============================================================
    "cyberpunk": {
        "name": "🩸 Cyberpunk",
        "category": "neon",
        "BG": "#0a0a0f",
        "BG_CARD": "#12121a",
        "BG_INPUT": "#1a1a25",
        "FG": "#e0ffe0",
        "FG_DIM": "#608080",
        "ACCENT": "#f7ff00",
        "ACCENT_HOVER": "#ffff66",
        "ACCENT_PRESS": "#c4cc00",
        "BORDER": "#1a2a2a",
        "BORDER_HOVER": "#f7ff00",
        "DISABLED": "#12121a",
        "DISABLED_FG": "#3d4d4d",
    },
    "matrix": {
        "name": "💚 Matrix",
        "category": "neon",
        "BG": "#000000",
        "BG_CARD": "#0a1a0a",
        "BG_INPUT": "#102a10",
        "FG": "#00ff41",
        "FG_DIM": "#008f11",
        "ACCENT": "#00ff41",
        "ACCENT_HOVER": "#66ff88",
        "ACCENT_PRESS": "#00aa22",
        "BORDER": "#003b00",
        "BORDER_HOVER": "#00ff41",
        "DISABLED": "#0a1a0a",
        "DISABLED_FG": "#003b00",
    },
    "cyber_red": {
        "name": "🔴 Cyber Red",
        "category": "neon",
        "BG": "#0a0000",
        "BG_CARD": "#1a0505",
        "BG_INPUT": "#2a0808",
        "FG": "#ff3333",
        "FG_DIM": "#8a1a1a",
        "ACCENT": "#ff0033",
        "ACCENT_HOVER": "#ff4466",
        "ACCENT_PRESS": "#cc0022",
        "BORDER": "#3a0808",
        "BORDER_HOVER": "#ff0033",
        "DISABLED": "#1a0505",
        "DISABLED_FG": "#4a1010",
    },
    "cyber_blue": {
        "name": "🔵 Cyber Blue",
        "category": "neon",
        "BG": "#00050f",
        "BG_CARD": "#050f1f",
        "BG_INPUT": "#0a1a2f",
        "FG": "#33ccff",
        "FG_DIM": "#1a6a8a",
        "ACCENT": "#00aaff",
        "ACCENT_HOVER": "#44ccff",
        "ACCENT_PRESS": "#0088cc",
        "BORDER": "#0a2a4a",
        "BORDER_HOVER": "#00aaff",
        "DISABLED": "#050f1f",
        "DISABLED_FG": "#0a3a5a",
    },
    "neon_pink": {
        "name": "💗 Neon Pink",
        "category": "neon",
        "BG": "#0f0008",
        "BG_CARD": "#1a0010",
        "BG_INPUT": "#2a0018",
        "FG": "#ff66cc",
        "FG_DIM": "#8a1a6a",
        "ACCENT": "#ff00aa",
        "ACCENT_HOVER": "#ff44bb",
        "ACCENT_PRESS": "#cc0088",
        "BORDER": "#3a0a2a",
        "BORDER_HOVER": "#ff00aa",
        "DISABLED": "#1a0010",
        "DISABLED_FG": "#4a1040",
    },
    "neon_orange": {
        "name": "🟧 Neon Orange",
        "category": "neon",
        "BG": "#0f0800",
        "BG_CARD": "#1a1000",
        "BG_INPUT": "#2a1a00",
        "FG": "#ff9933",
        "FG_DIM": "#8a5a1a",
        "ACCENT": "#ff6600",
        "ACCENT_HOVER": "#ffaa33",
        "ACCENT_PRESS": "#cc4400",
        "BORDER": "#3a2000",
        "BORDER_HOVER": "#ff6600",
        "DISABLED": "#1a1000",
        "DISABLED_FG": "#4a3000",
    },
    "neon_yellow": {
        "name": "💛 Neon Yellow",
        "category": "neon",
        "BG": "#0a0a00",
        "BG_CARD": "#141400",
        "BG_INPUT": "#1f1f00",
        "FG": "#ffff33",
        "FG_DIM": "#8a8a1a",
        "ACCENT": "#ffff00",
        "ACCENT_HOVER": "#ffff66",
        "ACCENT_PRESS": "#cccc00",
        "BORDER": "#3a3a00",
        "BORDER_HOVER": "#ffff00",
        "DISABLED": "#141400",
        "DISABLED_FG": "#4a4a00",
    },
    "cyber_purple": {
        "name": "🟣 Cyber Purple",
        "category": "neon",
        "BG": "#05000f",
        "BG_CARD": "#0f0520",
        "BG_INPUT": "#1a0a35",
        "FG": "#cc66ff",
        "FG_DIM": "#6a1a8a",
        "ACCENT": "#aa00ff",
        "ACCENT_HOVER": "#cc44ff",
        "ACCENT_PRESS": "#8800cc",
        "BORDER": "#2a0a4a",
        "BORDER_HOVER": "#aa00ff",
        "DISABLED": "#0f0520",
        "DISABLED_FG": "#3a0a5a",
    },
    "cyber_teal": {
        "name": "🩵 Cyber Teal",
        "category": "neon",
        "BG": "#000f0f",
        "BG_CARD": "#051a1a",
        "BG_INPUT": "#0a2a2a",
        "FG": "#33ffcc",
        "FG_DIM": "#1a8a6a",
        "ACCENT": "#00ffaa",
        "ACCENT_HOVER": "#44ffcc",
        "ACCENT_PRESS": "#00cc88",
        "BORDER": "#0a3a3a",
        "BORDER_HOVER": "#00ffaa",
        "DISABLED": "#051a1a",
        "DISABLED_FG": "#0a4a4a",
    },
    "synthwave": {
        "name": "🌴 Synthwave",
        "category": "neon",
        "BG": "#1a0033",
        "BG_CARD": "#2a0050",
        "BG_INPUT": "#3a006a",
        "FG": "#ff66cc",
        "FG_DIM": "#aa3388",
        "ACCENT": "#ff00ff",
        "ACCENT_HOVER": "#ff44ff",
        "ACCENT_PRESS": "#cc00cc",
        "BORDER": "#4a0080",
        "BORDER_HOVER": "#ff00ff",
        "DISABLED": "#2a0050",
        "DISABLED_FG": "#6a00a0",
    },
    # ============================================================
    #                    ПО ИГРАМ (game)
    # ============================================================
    "minecraft": {
        "name": "⛏️ Minecraft",
        "category": "game",
        "BG": "#1a2010",
        "BG_CARD": "#2a3018",
        "BG_INPUT": "#3a4020",
        "FG": "#e0e8c0",
        "FG_DIM": "#8a9a60",
        "ACCENT": "#7cb342",
        "ACCENT_HOVER": "#9ccc65",
        "ACCENT_PRESS": "#558b2f",
        "BORDER": "#3a4a20",
        "BORDER_HOVER": "#7cb342",
        "DISABLED": "#2a3018",
        "DISABLED_FG": "#5a6a35",
    },
    "doom": {
        "name": "😈 Doom",
        "category": "game",
        "BG": "#0a0000",
        "BG_CARD": "#1a0505",
        "BG_INPUT": "#2a0a0a",
        "FG": "#ff4444",
        "FG_DIM": "#8a1a1a",
        "ACCENT": "#ff0000",
        "ACCENT_HOVER": "#ff3333",
        "ACCENT_PRESS": "#aa0000",
        "BORDER": "#3a0a0a",
        "BORDER_HOVER": "#ff0000",
        "DISABLED": "#1a0505",
        "DISABLED_FG": "#5a1010",
    },
    "among_us": {
        "name": "🚀 Among Us",
        "category": "game",
        "BG": "#0a0a1a",
        "BG_CARD": "#14142a",
        "BG_INPUT": "#1e1e3a",
        "FG": "#ff4444",
        "FG_DIM": "#8a4444",
        "ACCENT": "#ff3333",
        "ACCENT_HOVER": "#ff6666",
        "ACCENT_PRESS": "#cc0000",
        "BORDER": "#2a2a4a",
        "BORDER_HOVER": "#ff3333",
        "DISABLED": "#14142a",
        "DISABLED_FG": "#5a3333",
    },
    "tron": {
        "name": "💠 TRON",
        "category": "game",
        "BG": "#000000",
        "BG_CARD": "#000a1a",
        "BG_INPUT": "#001428",
        "FG": "#00d4ff",
        "FG_DIM": "#006a99",
        "ACCENT": "#00d4ff",
        "ACCENT_HOVER": "#44e0ff",
        "ACCENT_PRESS": "#0099cc",
        "BORDER": "#003366",
        "BORDER_HOVER": "#00d4ff",
        "DISABLED": "#000a1a",
        "DISABLED_FG": "#003355",
    },
    "cyberpunk2077": {
        "name": "🌆 Cyberpunk 2077",
        "category": "game",
        "BG": "#0f0a1a",
        "BG_CARD": "#1a102a",
        "BG_INPUT": "#2a1a3a",
        "FG": "#fcee0a",
        "FG_DIM": "#8a7a1a",
        "ACCENT": "#fcee0a",
        "ACCENT_HOVER": "#ffff44",
        "ACCENT_PRESS": "#ccbb00",
        "BORDER": "#3a2a4a",
        "BORDER_HOVER": "#fcee0a",
        "DISABLED": "#1a102a",
        "DISABLED_FG": "#5a4a1a",
    },
    "persona5": {
        "name": "🎭 Persona 5",
        "category": "game",
        "BG": "#1a0000",
        "BG_CARD": "#2a0505",
        "BG_INPUT": "#3a0a0a",
        "FG": "#ffffff",
        "FG_DIM": "#aaaaaa",
        "ACCENT": "#ff0000",
        "ACCENT_HOVER": "#ff3333",
        "ACCENT_PRESS": "#cc0000",
        "BORDER": "#4a0a0a",
        "BORDER_HOVER": "#ff0000",
        "DISABLED": "#2a0505",
        "DISABLED_FG": "#666666",
    },
    "undertale": {
        "name": "❤️ Undertale",
        "category": "game",
        "BG": "#0a0a0a",
        "BG_CARD": "#1a1a1a",
        "BG_INPUT": "#2a2a2a",
        "FG": "#ffffff",
        "FG_DIM": "#888888",
        "ACCENT": "#ff3366",
        "ACCENT_HOVER": "#ff6688",
        "ACCENT_PRESS": "#cc0044",
        "BORDER": "#3a3a3a",
        "BORDER_HOVER": "#ff3366",
        "DISABLED": "#1a1a1a",
        "DISABLED_FG": "#555555",
    },
    "hollow_knight": {
        "name": "🦋 Hollow Knight",
        "category": "game",
        "BG": "#050a1a",
        "BG_CARD": "#0a142a",
        "BG_INPUT": "#0f1e3a",
        "FG": "#c0d8f0",
        "FG_DIM": "#5a7a9a",
        "ACCENT": "#4a9eff",
        "ACCENT_HOVER": "#77b8ff",
        "ACCENT_PRESS": "#2a7acc",
        "BORDER": "#1a2e4a",
        "BORDER_HOVER": "#4a9eff",
        "DISABLED": "#0a142a",
        "DISABLED_FG": "#3a4a6a",
    },
    "stardew": {
        "name": "🌾 Stardew Valley",
        "category": "game",
        "BG": "#1a1408",
        "BG_CARD": "#2a2010",
        "BG_INPUT": "#3a2c18",
        "FG": "#f0e0c0",
        "FG_DIM": "#aa8855",
        "ACCENT": "#d4a02a",
        "ACCENT_HOVER": "#f0b844",
        "ACCENT_PRESS": "#a87c18",
        "BORDER": "#4a3818",
        "BORDER_HOVER": "#d4a02a",
        "DISABLED": "#2a2010",
        "DISABLED_FG": "#6a5540",
    },
    "terraria": {
        "name": "🌳 Terraria",
        "category": "game",
        "BG": "#0a1a14",
        "BG_CARD": "#0f2a20",
        "BG_INPUT": "#143a2c",
        "FG": "#c0f0d8",
        "FG_DIM": "#6a9a80",
        "ACCENT": "#4ade80",
        "ACCENT_HOVER": "#77eaa0",
        "ACCENT_PRESS": "#2ab85e",
        "BORDER": "#1a4a38",
        "BORDER_HOVER": "#4ade80",
        "DISABLED": "#0f2a20",
        "DISABLED_FG": "#3d5a4a",
    },
    "portal": {
        "name": "🌀 Portal",
        "category": "game",
        "BG": "#0a0a0a",
        "BG_CARD": "#1a1a1a",
        "BG_INPUT": "#2a2a2a",
        "FG": "#e0e0e0",
        "FG_DIM": "#888888",
        "ACCENT": "#ff8800",
        "ACCENT_HOVER": "#ffaa33",
        "ACCENT_PRESS": "#cc6600",
        "BORDER": "#3a3a3a",
        "BORDER_HOVER": "#ff8800",
        "DISABLED": "#1a1a1a",
        "DISABLED_FG": "#666666",
    },
    "halflife": {
        "name": "🔶 Half-Life",
        "category": "game",
        "BG": "#1a0f00",
        "BG_CARD": "#2a1800",
        "BG_INPUT": "#3a2200",
        "FG": "#ffcc88",
        "FG_DIM": "#aa7744",
        "ACCENT": "#ff8800",
        "ACCENT_HOVER": "#ffaa44",
        "ACCENT_PRESS": "#cc5500",
        "BORDER": "#4a2800",
        "BORDER_HOVER": "#ff8800",
        "DISABLED": "#2a1800",
        "DISABLED_FG": "#6a4422",
    },

    # ============================================================
    #                    ПО ВАЙБУ (vibe)
    # ============================================================
    "vaporwave": {
        "name": "🌴 Vaporwave",
        "category": "vibe",
        "BG": "#1a0a1a",
        "BG_CARD": "#2a102a",
        "BG_INPUT": "#3a1a3a",
        "FG": "#ffb3d9",
        "FG_DIM": "#aa5588",
        "ACCENT": "#ff66cc",
        "ACCENT_HOVER": "#ff99dd",
        "ACCENT_PRESS": "#cc3399",
        "BORDER": "#4a204a",
        "BORDER_HOVER": "#ff66cc",
        "DISABLED": "#2a102a",
        "DISABLED_FG": "#6a4060",
    },
    "y2k": {
        "name": "💿 Y2K",
        "category": "vibe",
        "BG": "#1a1a2a",
        "BG_CARD": "#2a2a3a",
        "BG_INPUT": "#3a3a4a",
        "FG": "#c0c0e0",
        "FG_DIM": "#8888aa",
        "ACCENT": "#aaffee",
        "ACCENT_HOVER": "#ccffff",
        "ACCENT_PRESS": "#77ddcc",
        "BORDER": "#4a4a5a",
        "BORDER_HOVER": "#aaffee",
        "DISABLED": "#2a2a3a",
        "DISABLED_FG": "#555566",
    },
    "noir": {
        "name": "🎩 Noir",
        "category": "vibe",
        "BG": "#0a0a0a",
        "BG_CARD": "#1a1a1a",
        "BG_INPUT": "#2a2a2a",
        "FG": "#e0e0e0",
        "FG_DIM": "#888888",
        "ACCENT": "#cccccc",
        "ACCENT_HOVER": "#ffffff",
        "ACCENT_PRESS": "#999999",
        "BORDER": "#3a3a3a",
        "BORDER_HOVER": "#cccccc",
        "DISABLED": "#1a1a1a",
        "DISABLED_FG": "#555555",
    },
    "sepia": {
        "name": "📷 Sepia",
        "category": "vibe",
        "BG": "#1a140a",
        "BG_CARD": "#2a2010",
        "BG_INPUT": "#3a2c18",
        "FG": "#e8d4b0",
        "FG_DIM": "#a08560",
        "ACCENT": "#b08850",
        "ACCENT_HOVER": "#d0a870",
        "ACCENT_PRESS": "#886030",
        "BORDER": "#4a3818",
        "BORDER_HOVER": "#b08850",
        "DISABLED": "#2a2010",
        "DISABLED_FG": "#665540",
    },
    "neon_tokyo": {
        "name": "🗼 Neon Tokyo",
        "category": "vibe",
        "BG": "#0f0518",
        "BG_CARD": "#1a0a28",
        "BG_INPUT": "#2a1038",
        "FG": "#ffb3e6",
        "FG_DIM": "#aa66aa",
        "ACCENT": "#ff00aa",
        "ACCENT_HOVER": "#ff44cc",
        "ACCENT_PRESS": "#cc0088",
        "BORDER": "#3a1a4a",
        "BORDER_HOVER": "#ff00aa",
        "DISABLED": "#1a0a28",
        "DISABLED_FG": "#5a3a5a",
    },
    "brat": {
        "name": "🟩 Brat",
        "category": "vibe",
        "BG": "#0a1a0a",
        "BG_CARD": "#102a10",
        "BG_INPUT": "#183a18",
        "FG": "#8ace00",
        "FG_DIM": "#4a7a00",
        "ACCENT": "#8ace00",
        "ACCENT_HOVER": "#aaee33",
        "ACCENT_PRESS": "#6a9a00",
        "BORDER": "#1a4a1a",
        "BORDER_HOVER": "#8ace00",
        "DISABLED": "#102a10",
        "DISABLED_FG": "#3a5a10",
    },
    "skibidi": {
        "name": "🚽 Skibidi",
        "category": "vibe",
        "BG": "#0a0a0a",
        "BG_CARD": "#1a1a1a",
        "BG_INPUT": "#2a2a2a",
        "FG": "#ffffff",
        "FG_DIM": "#999999",
        "ACCENT": "#00ccff",
        "ACCENT_HOVER": "#44ddff",
        "ACCENT_PRESS": "#0099cc",
        "BORDER": "#3a3a3a",
        "BORDER_HOVER": "#00ccff",
        "DISABLED": "#1a1a1a",
        "DISABLED_FG": "#555555",
    },
    "cozy": {
        "name": "🧸 Cozy",
        "category": "vibe",
        "BG": "#2a1f18",
        "BG_CARD": "#3a2c22",
        "BG_INPUT": "#4a3a2c",
        "FG": "#f0dcc4",
        "FG_DIM": "#aa8a6a",
        "ACCENT": "#d4a574",
        "ACCENT_HOVER": "#e8c090",
        "ACCENT_PRESS": "#a87c50",
        "BORDER": "#5a4530",
        "BORDER_HOVER": "#d4a574",
        "DISABLED": "#3a2c22",
        "DISABLED_FG": "#6a5540",
    },
    "brutalist": {
        "name": "🏢 Brutalist",
        "category": "vibe",
        "BG": "#1a1a1a",
        "BG_CARD": "#2a2a2a",
        "BG_INPUT": "#3a3a3a",
        "FG": "#d0d0d0",
        "FG_DIM": "#888888",
        "ACCENT": "#ff6600",
        "ACCENT_HOVER": "#ff8833",
        "ACCENT_PRESS": "#cc4400",
        "BORDER": "#4a4a4a",
        "BORDER_HOVER": "#ff6600",
        "DISABLED": "#2a2a2a",
        "DISABLED_FG": "#666666",
    },
    "artdeco": {
        "name": "✨ Art Deco",
        "category": "vibe",
        "BG": "#0a0a0a",
        "BG_CARD": "#1a1a0a",
        "BG_INPUT": "#2a2a10",
        "FG": "#f0ddaa",
        "FG_DIM": "#aa8855",
        "ACCENT": "#d4af37",
        "ACCENT_HOVER": "#e8c860",
        "ACCENT_PRESS": "#a88a20",
        "BORDER": "#3a3a15",
        "BORDER_HOVER": "#d4af37",
        "DISABLED": "#1a1a0a",
        "DISABLED_FG": "#6a5a30",
    },
    "retrowave": {
        "name": "🌇 Retrowave",
        "category": "vibe",
        "BG": "#1a0a2a",
        "BG_CARD": "#2a1040",
        "BG_INPUT": "#3a1a55",
        "FG": "#ffb088",
        "FG_DIM": "#aa5577",
        "ACCENT": "#ff4466",
        "ACCENT_HOVER": "#ff6688",
        "ACCENT_PRESS": "#cc2244",
        "BORDER": "#4a2065",
        "BORDER_HOVER": "#ff4466",
        "DISABLED": "#2a1040",
        "DISABLED_FG": "#6a4060",
    },
    "zen": {
        "name": "☯️ Zen",
        "category": "vibe",
        "BG": "#1a1a1a",
        "BG_CARD": "#2a2a2a",
        "BG_INPUT": "#3a3a3a",
        "FG": "#c8c8c8",
        "FG_DIM": "#808080",
        "ACCENT": "#a0a0a0",
        "ACCENT_HOVER": "#c0c0c0",
        "ACCENT_PRESS": "#707070",
        "BORDER": "#4a4a4a",
        "BORDER_HOVER": "#a0a0a0",
        "DISABLED": "#2a2a2a",
        "DISABLED_FG": "#555555",
    },
}


# ============================================================
#                    КАТЕГОРИИ
# ============================================================
CATEGORIES = {
    "all":     "🎨 Все",
    "dark":    "🌙 Тёмные",
    "light":   "☀️ Светлые",
    "holiday": "🎃 Праздники",
    "code":    "💻 Программистские",
    "neon":    "⚡ Неон",
    "custom":  "✨ Свои",
    "game":    "🎮 Игры",
    "vibe":    "🎨 Вайб",
}


def themes_by_category(category):
    """Возвращает список (key, theme) в указанной категории."""
    result = []
    for key, t in THEMES.items():
        if key.startswith("custom_"):
            continue
        cat = t.get("category", "dark")
        if category == "all" or cat == category:
            result.append((key, t))
    return result


# регистрируем кастомные темы при импорте
try:
    from modules import theme_manager
    theme_manager.register_custom_themes(THEMES)
except Exception as _e:
    print(f"⚠️ Не удалось загрузить кастомные темы: {_e}")


def get_theme(name):
    """Возвращает палитру по имени. Если нет — тёмная."""
    if name not in THEMES:
        try:
            from modules import theme_manager
            theme_manager.register_custom_themes(THEMES)
        except Exception:
            pass
    return THEMES.get(name, THEMES["dark"])