# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['downloader_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icons', 'icons'),
        ('icon.ico', '.'),
        ('CHANGELOG.md', '.'),
        ('cover.png', '.'),
        ('ffmpeg.exe', '.'),
    ],
    hiddenimports=[
        # системные модули
        'config',
        'settings',
        # папка modules целиком
        'modules',
        'modules.bootstrap',
        'modules.core',
        'modules.settings',
        'modules.gui_qt',
        'modules.gui_dark',
        'modules.launcher_qt',
        'modules.launcher_dark',
        'modules.themes',
        'modules.theme_manager',
        'modules.theme_configurator',
        'modules.icons',
        'modules.icon_manager',
        'modules.icon_maker',
        'modules.visual',
        'modules.embed',
        'modules.cache',
        'modules.tray',
        'modules.sounds',
        'modules.toast',
        'modules.splash',
        'modules.updater',
        'modules.falling_fx',
        'modules.falling_fx_qt',
        # сторонние
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'tkinter',
        'yt_dlp',
        'mutagen',
        'PIL',
        'numpy',
        'pygame',
        'pystray',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='YouTubeDownloader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    icon=['icon.ico'],
)